FROM gcr.io/distroless/static-debian12:nonroot
COPY external-dns-libdns-webhook /external-dns-libdns-webhook
# nonroot, match external-dns default securityContext
USER 65532:65532
ENTRYPOINT ["/external-dns-libdns-webhook"]